### PR TITLE
PSG-1097: replace Path with str in the generation of resultfiles.json so that we can process both FS paths and S3 URIs

### PR DESCRIPTION
**Pull request by pdp10**
**the validation script currently fails on jenkins int test - let me fix this before reviewing**

This PR fixes the paths in the resultfiles.json (`s3:/bucket/file` -> `s3://bucket/file`).

Additional test:
```
root@sars-cov-2-pipeline-minikube-86db564bc9-sr5j5:/app/psga# nextflow run . --run ont_short --sequencing_technology ont --kit ARTIC_V3 --metadata s3://synthetic-data-dev/UKHSA/small_tests/ont/metadata.csv --output_path s3://synthetic-data-dev/UKHSA/piero_test_remove
N E X T F L O W  ~  version 22.08.0-edge
Launching `./main.nf` [deadly_mandelbrot] DSL2 - revision: b450160779
[4b/9ad1fa] Submitted process > psga:pipeline_start
[0e/78081d] Submitted process > psga:check_metadata (metadata.csv)
[02/bd67aa] Submitted process > psga:stage_sample_file (1 - d3e958b5-0c56-48d6-807b-6a89f61408ce.bam)
[aa/9eab5f] Submitted process > psga:stage_fastq_sample_file (1 - 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fq.gz)
[9c/42f34e] Submitted process > psga:bam_to_fastq (1 - d3e958b5-0c56-48d6-807b-6a89f61408ce.bam)
[a8/15aa1f] Submitted process > psga:stage_fastq_sample_file (2 - b833399a-4d49-4d00-abdb-39d5086a5a0d.fastq)
[4c/b86e51] Submitted process > psga:contamination_removal (1 - 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fq.gz)
[89/29f112] Submitted process > psga:contamination_removal (2 - b833399a-4d49-4d00-abdb-39d5086a5a0d.fastq)
[1d/fc3d31] Submitted process > psga:contamination_removal (3 - d3e958b5-0c56-48d6-807b-6a89f61408ce.fastq)
[d1/7e7340] Submitted process > psga:fastqc (1 - 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fastq.gz)
[10/6bcd8f] Submitted process > psga:fastqc (2 - b833399a-4d49-4d00-abdb-39d5086a5a0d.fastq.gz)
[50/0f6358] Submitted process > psga:fastqc (3 - d3e958b5-0c56-48d6-807b-6a89f61408ce.fastq.gz)
[1c/e9f6db] Submitted process > psga:ncov2019_artic (1 - 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fastq.gz)
[68/1e9892] Submitted process > psga:ncov2019_artic (2 - b833399a-4d49-4d00-abdb-39d5086a5a0d.fastq.gz)
[ae/2f2f99] Submitted process > psga:ncov2019_artic (3 - d3e958b5-0c56-48d6-807b-6a89f61408ce.fastq.gz)
[6b/0eb338] Submitted process > psga:reheader:reheader_fasta (1 - [b833399a-4d49-4d00-abdb-39d5086a5a0d.qc.csv, b833399a-4d49-4d00-abdb-39d5086a5a0d.consensus.fa])
[25/758c9b] Submitted process > psga:reheader:store_reheadered_qc_passed_fasta (1 - b833399a-4d49-4d00-abdb-39d5086a5a0d.fasta)
[69/269d34] Submitted process > psga:pangolin (1 - b833399a-4d49-4d00-abdb-39d5086a5a0d.fasta)
[fb/7ddb35] Submitted process > psga:reheader:reheader_fasta (2 - [d3e958b5-0c56-48d6-807b-6a89f61408ce.qc.csv, d3e958b5-0c56-48d6-807b-6a89f61408ce.consensus.fa])
[4e/54730d] Submitted process > psga:reheader:store_reheadered_qc_passed_fasta (2 - d3e958b5-0c56-48d6-807b-6a89f61408ce.fasta)
[59/172fcc] Submitted process > psga:pangolin (2 - d3e958b5-0c56-48d6-807b-6a89f61408ce.fasta)
[51/c11ca1] Submitted process > psga:reheader:reheader_fasta (3 - [2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.qc.csv, 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.consensus.fa])
[21/a739dd] Submitted process > psga:submit_analysis_run_results:submit_ncov_results
[68/31cfc1] Submitted process > psga:reheader:store_reheadered_qc_passed_fasta (3 - 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fasta)
[9a/3213d4] Submitted process > psga:pangolin (3 - 2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fasta)
[95/16eb15] Submitted process > psga:submit_analysis_run_results:submit_pangolin_results
[45/860fcc] Submitted process > psga:submit_analysis_run_results:submit_pipeline_results_files
[fd/58ded0] Submitted process > pipeline_end

root@sars-cov-2-pipeline-minikube-86db564bc9-sr5j5:/app/psga# aws s3 cp s3://synthetic-data-dev/UKHSA/piero_test_remove/resultfiles.json .
download: s3://synthetic-data-dev/UKHSA/piero_test_remove/resultfiles.json to ./resultfiles.json

root@sars-cov-2-pipeline-minikube-86db564bc9-sr5j5:/app/psga# head ./resultfiles.json 
{
    "2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb": [
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/contamination_removal/cleaned_fastq/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.fastq.gz",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/contamination_removal/counting/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.txt",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/fastqc/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb_fastqc.zip",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/ncov2019-artic/output_bam/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.primertrimmed.rg.sorted.bam",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/ncov2019-artic/output_bam/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.primertrimmed.rg.sorted.bam.bai",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/ncov2019-artic/output_fasta/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.consensus.fa",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/ncov2019-artic/output_fasta/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.preconsensus.fa",
        "s3://synthetic-data-dev/UKHSA/piero_test_remove/ncov2019-artic/output_variants/2cf78ed4-edae-4943-ab04-5d7a1e4cbdcb.pass.vcf.gz",
```

### CODE REVIEW

**Review by cramshaw — APPROVED** [review]
I can't see any updates on this to the tests or how it changes the output paths, but it looks solid, thanks Piero!

**Comment by pdp10** [comment]
> I can't see any updates on this to the tests or how it changes the output paths, but it looks solid, thanks Piero!

It's just a change from Path to str so that we can deal with both filesystem paths and s3 uri. There are only string concatenations, so no need for specific s3 tests.

**Comment by cramshaw** [comment]
Ok great - let's give it a go then!

**Comment by pdp10** [comment]
> Ok great - let's give it a go then!

I've added them anyway: https://github.com/Congenica/psga-pipeline/pull/125/files#diff-b221e7681e0b7e06e3bae6f846dcd94df4983cc0ac9758d55e282dcb269202d6 :)

**Pull request merged**
