### PR TITLE
PSG-1885: prefix ncov_ or pangolin_ to the corresponding column names in the results file

### PR DESCRIPTION
**Pull request by pdp10**
As part of this PR, I've also updated the column name `VERSION` to `PANGOLIN_PANGO_DESIGNATION_VERSION`.

Example of JSON output generated from the CSV:
```
    "aff01b7c-8a0a-40bf-927a-0548add8ea5a": {
        "CONTAMINATED_READS": "696",
        "NCOV_LONGEST_NO_N_RUN": "10310",
        "NCOV_NUM_ALIGNED_READS": "273604",
        "NCOV_PCT_COVERED_BASES": "97.45",
        "NCOV_PCT_N_BASES": "2.48",
        "NCOV_QC_PASS": "True",
        "PANGOLIN_AMBIGUITY_SCORE": "",
        "PANGOLIN_CONFLICT": "0.0",
        "PANGOLIN_CONSTELLATION_VERSION": "v0.1.10",
        "PANGOLIN_IS_DESIGNATED": "False",
        "PANGOLIN_LINEAGE": "AY.98",
        "PANGOLIN_NOTE": "Usher placements: AY.98(1/1)",
        "PANGOLIN_PANGO_DESIGNATION_VERSION": "PUSHER-v1.16",
        "PANGOLIN_QC_NOTES": "Ambiguous_content:0.04",
        "PANGOLIN_QC_STATUS": "pass",
        "PANGOLIN_SCORPIO_CALL": "Delta (B.1.617.2-like)",
        "PANGOLIN_SCORPIO_CONFLICT": "0.0",
        "PANGOLIN_SCORPIO_NOTES": "scorpio call: Alt alleles 13; Ref alleles 0; Amb alleles 0; Oth alleles 0",
        "PANGOLIN_SCORPIO_SUPPORT": "1.0",
        "PANGOLIN_SCORPIO_VERSION": "0.3.17",
        "PANGOLIN_VERSION": "4.1.3",
        "PRIMER_COVERAGE": "0.5688073394495413",
        "PRIMER_DETECTED": "ARTIC_V3",
        "PRIMER_INPUT": "unknown",
        "PRIMER_NUMREADS": "489",
        "PRIMER_UNIQUE_NUMREADS": "62",
        "STATUS": "Completed"
    }
```

### CODE REVIEW

**Review by PatrickJordanCongenica — APPROVED** [review]
LGTM Piero, thanks!

**Comment by PatrickJordanCongenica** [comment]
@cramshaw I imagine we'd want to also updated the example responses in the Swagger docs for the sample endpoints?

**Comment by pdp10** [comment]
> @cramshaw I imagine we'd want to also updated the example responses in the Swagger docs for the sample endpoints?

@PatrickJordanCongenica  is this addressed in this other ticket? https://jira.congenica.net/browse/PSG-1916

**Comment by PatrickJordanCongenica** [comment]
> > @cramshaw I imagine we'd want to also updated the example responses in the Swagger docs for the sample endpoints?
> 
> @PatrickJordanCongenica is this addressed in this other ticket? https://jira.congenica.net/browse/PSG-1916

Yep, thanks for confirming!

**Comment by Aiky30** [comment]
@pdp10 When do you plan to merge this change, it could break the backend before tomorrows release?

**Comment by pdp10** [comment]
Merged on Sangya's request.

**Pull request merged**
